name: ci-cd-workflow

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: .docker/Dockerfile.production
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bo-2.0-frontend:latest
          secrets: |
            "API_BASE_URL=${{ secrets.API_BASE_URL}}"
            "CLIENT_ID=${{ secrets.CLIENT_ID}}"
            "CLIENT_SECRET=${{ secrets.CLIENT_SECRET}}"

      - name: Docker Pull & Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bo-2.0-frontend:latest
            docker ps -q --filter "name=bo-2.0-frontend" | grep -q . && docker stop bo-2.0-frontend
            docker run -d --rm -p 8080:3000 --name bo-2.0-frontend --network blueotter_network ${{ secrets.DOCKERHUB_USERNAME }}/bo-2.0-frontend